apiVersion: v1
kind: Service
metadata:
  {{- if eq .Values.AlertManager.Service.Type "LoadBalancer" }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
  {{- end }}
  name: {{ template "fullname" . }}
  namespace: {{ .Values.Namespace | default "default" }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: {{ template "fullname" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
spec:
  ports:
  - name: "http"
    port: {{ .Values.AlertManager.Port.Service }}
    protocol: "TCP"
    targetPort: "http"
  selector:
    component: {{ template "fullname" . }}
  type: {{ .Values.AlertManager.Service.Type }}
  {{- if eq .Values.AlertManager.Service.Type "LoadBalancer" }}
  loadBalancerSourceRanges: {{ .Values.AlertManager.LoadBalancer.SourceRanges }}
  {{- end }}
